version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    working_directory: ~/myproject
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python tests.py
